version: "3.9"
services:
    php:
        build: ./docker/php
        container_name: ff_php
        volumes:
            - ./:/var/www/html:cached
        environment:
            APP_ENV: dev
            PHP_IDE_CONFIG: serverName=php
        restart: unless-stopped

    nginx:
        build: ./docker/nginx
        container_name: ff_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:ro
        depends_on:
            - php
        restart: unless-stopped

