services:
    nginx:
      image: nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: dev
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./docker/src:/var/www/html:ro,cached
      depends_on:
        - symfony
      links:
        - symfony

    symfony: &symfony-template
      image: symfony:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: ${UID:-1000}
          HOST_GID: ${GID:-1000}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-symfony
      expose:
        - 9000
      volumes:
        - ./docker/src:/var/www/html:cached
